/*
 * Generated by ISE 25.02.9.8732 - win64
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F258_6007();
extern void F260_6169();
extern void F258_6011();
extern void F261_6173();
extern void F263_6337();
extern void F261_6178();
extern void F380_3854();
extern void F356_5853();
extern void F129_1558();
extern EIF_REFERENCE F129_1545();
extern EIF_BOOLEAN F129_1557();
extern EIF_BOOLEAN F129_1565();
extern void F129_1567();
extern void F129_1568();
extern void F129_1569();
extern void F70_1216();
extern EIF_TYPED_VALUE F70_1217();

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;


extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F258_6007;
	egc_immstr8make_from_c_byte_array = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F258_6011;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F261_6173;
	egc_immstr32make_from_c_byte_array = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F261_6178;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F380_3854;
	egc_strset = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F260_6169;
	egc_str32set = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F263_6337;
	egc_routdisp_wb = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F356_5853;
	egc_is_scoop_capable = 0;
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F129_1558;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F129_1557;
	egc_last_exception = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F129_1545;
	egc_is_code_ignored = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F129_1565;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F129_1567;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F129_1568;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F129_1569;

	egc_str_dtype = 259;

	egc_immstr8_dtype = 258;

	egc_str32_dtype = 262;

	egc_immstr32_dtype = 261;
	egc_arr_dtype = 379;
	egc_tup_dtype = 211;
	egc_disp_rout_id = 2187;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = 0x028E;
	egc_sp_wchar = 0x01D1;
	egc_sp_bool = 0x039C;
	egc_sp_uint8 = 0x0378;
	egc_sp_uint16 = 0x0354;
	egc_sp_uint32 = 0x0226;
	egc_sp_uint64 = 0x01ED;
	egc_sp_int8 = 0x030C;
	egc_sp_int16 = 0x02E8;
	egc_sp_int32 = 0x019C;
	egc_sp_int64 = 0x0330;
	egc_sp_real32 = 0x02A0;
	egc_sp_real64 = 0x02C4;
	egc_sp_pointer = 0x024D;
	egc_sp_ref = 0x017A;

	egc_uint8_dtype = 234;
	egc_uint16_dtype = 231;
	egc_uint32_dtype = 228;
	egc_uint64_dtype = 225;
	egc_int8_dtype = 222;
	egc_int16_dtype = 219;
	egc_int32_dtype = 216;
	egc_int64_dtype = 213;
	egc_bool_dtype = 249;
	egc_real32_dtype = 237;
	egc_char_dtype = 246;
	egc_wchar_dtype = 243;
	egc_real64_dtype = 240;
	egc_point_dtype = 252;

	egc_exception_dtype = 88;
	egc_except_emnger_dtype = 128;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	egc_foption = egc_foption_init;
	egc_frozen = egc_frozen_init;
	egc_fpatidtab = egc_fpatidtab_init;
	egc_address_table = egc_address_table_init;
	egc_fpattern = egc_fpattern_init;

	egc_einit = egc_einit_init;
	egc_tabinit = egc_tabinit_init;
	egc_forg_table = egc_forg_table_init;

	egc_system_name = "simple_htmx";
	egc_system_location = "D:\\prod\\simple_htmx\\EIFGENs\\simple_htmx_tests\\W_code";
	egc_compiler_tag = 39;
	egc_project_version = 1764776196;
	egc_has_old_special_semantic = 0;
	scount = 1014;

	egc_rcount = 3;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcrid = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcarg = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "APPLICATION.make";
	egc_rcdt[0] = 0;
	egc_rcrid[0] = 674;
	egc_rcarg[0] = 0;
	
	egc_rlist[1] = "EQA_EVALUATOR.make";
	egc_rcdt[1] = 0;
	egc_rcrid[1] = 2758;
	egc_rcarg[1] = 0;
	
	egc_rlist[2] = "ITP_INTERPRETER.execute";
	egc_rcdt[2] = 0;
	egc_rcrid[2] = 5248;
	egc_rcarg[2] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_rt_extension_dt = 69;
	egc_rt_extension_notify = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F70_1216;
	egc_rt_extension_notify_argument = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F70_1217;
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 26; /* APPLICATION */
	}if (egc_rcdt[1] == 0) {
		egc_rcdt[1] = 182; /* EQA_EVALUATOR */
	}if (egc_rcdt[2] == 0) {
		egc_rcdt[2] = 310; /* ITP_INTERPRETER */
	}
}

#ifdef __cplusplus
}
#endif
